Areas/HolidayPot/Models/Holidays.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace DatePot.Areas.HolidayPot.Models
{
    public class Holidays
    {
        public class HolidayIndex
        {
            public List<HolidayList> HolidayList { get; set; }
        }
        public class HolidayList
        {
            [Key]
            public int HolidayID { get; set; }
            [Display(Name = "Name")]
            public string Country { get; set; }
            public string City { get; set; }
            public string Been { get; set; }
            public string DateBeen { get; set; }
            public int? UserGroupID { get; set; }
        }
        public class NewHoliday
        {
            [Required]
            public string Country { get; set; }
            [Required]
            public string City { get; set; }
            [Required]
            public bool Been { get; set; }
            public DateTime? DateBeen { get; set; }
        }
        public class HolidayDetails
        {
            [Key]
            public int HolidayID { get; set; }
            [Display(Name = "Name")]
            public string Country { get; set; }
            public string City { get; set; }
            public bool Been { get; set; }
            public DateTime DateBeen { get; set; }
            public int? UserGroupID { get; set; }
        }
        public class UpdateHolidayDetails : HolidayDetails
        {
            public IFormFile FormFile { get; set; }
        }
        public class FileModel
        {
            public string FileName { get; set; }
        }
    }
}

Areas/HolidayPot/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using static DatePot.Areas.HolidayPot.Models.Holidays;
using DatePot.Areas.HolidayPot.Data;
using static DatePot.Models.Site;
using Microsoft.AspNetCore.Identity;
using DatePot.Areas.Identity.Data;
using DatePot.Data;
using Microsoft.AspNetCore.Http;
using Serilog;

namespace DatePot.Areas.HolidayPot.Pages
{
    [ValidateAntiForgeryToken]
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		private readonly IConfiguration _config;
		private readonly IHolidayData _HolidayData;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IIdentityData _identityData;
		private readonly ISiteData _siteData;
		public IndexModel(ILogger<IndexModel> logger,
		IConfiguration config,
		IHolidayData HolidayData,
		UserManager<IdentityUser> userManager,
		IIdentityData identityData,
		ISiteData siteData)
		{
			_logger = logger;
			_config = config;
			_HolidayData = HolidayData;
			_userManager = userManager;
			_identityData = identityData;
			_siteData = siteData;
		}
		public List<HolidayList> Holidays { get; set; }
		public NewHoliday NewHoliday { get; set; }
		public List<PotAccess> PotAccess { get; set; }
		public async Task<ActionResult> OnGet()
		{
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToPage("/Account/Login", new { area = "Identity" });
			}
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				var user = await _userManager.GetUserAsync(User);
				PotAccess = await _siteData.GetPotAccess(user.Id.ToString(), UserGroupID);
				int index = PotAccess.FindIndex(item => item.PotID == 7);
				if (index == -1)
				{
					return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
				}
				Holidays = _HolidayData.GetHolidayList(UserGroupID).Result;

				return Page();
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<JsonResult> OnPost(string Country, string City, bool Been, DateTime? DateBeen)
		{
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				JsonResult result = null;
				if (ModelState.IsValid == false)
				{
					foreach (var modelStateKey in ViewData.ModelState.Keys)
					{
						var value = ViewData.ModelState[modelStateKey];
						foreach (var error in value.Errors)
						{
							var errorMessage = error.ErrorMessage;
							result = new JsonResult(modelStateKey + ": " + errorMessage);
						}
					}
					return result;
				}
				int HolidayID = _HolidayData.AddHoliday(Country, City, Been, DateBeen, UserGroupID).Result;

				result = new JsonResult(HolidayID);
				return result;
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
	}
}

Areas/HolidayPot/Pages/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using static DatePot.Areas.HolidayPot.Models.Holidays;
using DatePot.Areas.HolidayPot.Data;
using static DatePot.Models.Site;
using Microsoft.AspNetCore.Identity;
using DatePot.Areas.Identity.Data;
using DatePot.Data;
using Microsoft.AspNetCore.Http;
using DatePot.Areas.FilmPot.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Serilog;

namespace DatePot.Areas.HolidayPot.Pages
{
    [ValidateAntiForgeryToken]
    public class ViewModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly IHolidayData _HolidayData;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IIdentityData _identityData;
        private readonly ISiteData _siteData;
        private readonly IFilmData _filmData;
        private IHostingEnvironment _environment;
        public ViewModel(IConfiguration config,
        IHolidayData HolidayData,
        UserManager<IdentityUser> userManager,
        IIdentityData identityData,
        ISiteData siteData,
        IFilmData filmData,
        IHostingEnvironment environment)
        {
            _config = config;
            _HolidayData = HolidayData;
            _userManager = userManager;
            _identityData = identityData;
            _siteData = siteData;
            _filmData = filmData;
            _environment = environment;
        }
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty]
        public UpdateHolidayDetails UpdateHolidayDetails { get; set; }
        [BindProperty]
        public List<FileModel> FileNameList { get; set; }
        public List<string> FileNames { get; set; }
        public HolidayDetails HolidayDetails { get; set; }
        public List<PotAccess> PotAccess { get; set; }
        public List<SelectListItem> Users { get; set; }
        public async Task<IActionResult> OnGet()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }
            try
            {
                int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
                var user = await _userManager.GetUserAsync(User);
                PotAccess = await _siteData.GetPotAccess(user.Id.ToString(), UserGroupID);
                int index = PotAccess.FindIndex(item => item.PotID == 7);
                if (index == -1)
                {
                    return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
                }
                string cs = _config.GetConnectionString("Default");
                HolidayDetails = _HolidayData.GetHolidayDetails(Id).Result.FirstOrDefault();               
                //Fetch all files in the Folder (Directory).
                string holidayPath = "images\\Holiday\\" + Id;
                var path = Path.Combine(_environment.WebRootPath, holidayPath);
                if (!Directory.Exists(path)) {
                    Directory.CreateDirectory(path);
                }
                string[] filePaths = Directory.GetFiles(path);

                //Copy File names to Model collection.
                FileNameList = new List<FileModel>();
                foreach (string filePath in filePaths)
                {
                    FileNameList.Add(new FileModel { FileName = Id + "/" + Path.GetFileName(filePath) });
                }
                if (HolidayDetails.UserGroupID != UserGroupID)
                {
                    return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
                }
                return Page();
            }
            catch (Exception ex)
            {
				Log.Error(ex.ToString());
                throw new Exception(ex.ToString());
            }
        }
        public async Task<IActionResult> OnPost()
        {
            try
            {
                string cs = _config.GetConnectionString("Default");
                await _HolidayData.UpdateHoliday(Convert.ToInt16(Request.Form["UpdateHolidayDetails.HolidayID"]),
                    Request.Form["UpdateHolidayDetails.Country"].ToString(),
                    Request.Form["UpdateHolidayDetails.City"].ToString(),
                    Convert.ToBoolean(Request.Form["UpdateHolidayDetails.Been"].ToString()),
                    Request.Form["UpdateHolidayDetails.DateBeen"].ToString());
                return RedirectToPage("./View", new { @Id = Request.Form["UpdateHolidayDetails.HolidayID"].ToString(), @redirect = "update" });
            }
            catch (Exception ex)
            {
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
            }
        }
        public async Task<IActionResult> OnPostFileUploadAsync(IFormFile[] photos)
        {
            try
            {

                string Id = HttpContext.Request.Form["HolidayID"].ToString();
                if (photos != null && photos.Length > 0)
                {
                    FileNames = new List<string>();
                    foreach (IFormFile photo in photos)
                    {
                        string holidayPath = "images\\Holiday\\" + Id;
                        var path = Path.Combine(_environment.WebRootPath, holidayPath, photo.FileName);
                        var stream = new FileStream(path, FileMode.Create);
                        photo.CopyToAsync(stream);
                        FileNames.Add(photo.FileName);
                    }
                }
                return RedirectToPage("./View", new { @Id = Id, @redirect = "update" });
            }
            catch (Exception ex)
            {
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
            }
        }
        public async Task<IActionResult> OnPostArchive()
        {
            try
            {
                if (ModelState.IsValid == false)
                {
                    return Page();
                }
                string cs = _config.GetConnectionString("Default");
                await _HolidayData.ArchiveHoliday(UpdateHolidayDetails.HolidayID);

                return RedirectToPage("./Index");
            }
            catch (Exception ex)
            {
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
            }
        }
    }
}

Areas/HolidayPot/Pages/Index.cshtml
@page
@model DatePot.Areas.HolidayPot.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="fadeIn">
    <div class="row">
        <div class="col-12">
            <button type="button" class="btn btn-primary btnAddHolidayModal btnHolidayButtons" data-toggle="modal"
                data-target="#AddHolidayModal">Add Holiday</button>
        </div>
    </div>
    <div class="row pt-4">
        <div class="col-12">
            <table id="HolidayTable"
                class="table table-striped table-stripedHolidayPot table-borderless ClientSearchTable Holidayrow">
                <thead class="thead-darkHolidaytable">
                    <tr>
                        <th>Country</th>
                        <th>City</th>
                        <th>Been</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Holidays)
                    {
                        <tr>
                            <td>
                                @item.Country
                            </td>
                            <td>
                                @item.City
                            </td>
                            <td>
                                @item.Been
                            </td>
                            <td>
                                @item.DateBeen
                            </td>
                            <td>
                                <a asp-page="/View" asp-route-Id="@item.HolidayID">View</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="AddHolidayModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Holiday destination</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post">
                @Html.AntiForgeryToken()
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div lcass="form-group">
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="NewHoliday.Country" class="control-label"></label>
                                <input asp-for="NewHoliday.Country" class="form-control NewHolidayCountry"
                                    required="required" type="text" />
                                <span asp-validation-for="NewHoliday.Country" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="NewHoliday.City" class="control-label"></label>
                                <input asp-for="NewHoliday.City" class="form-control NewHolidayCity" required="required"
                                    type="text" />
                                <span asp-validation-for="NewHoliday.City" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="NewHoliday.Been" class="control-label"></label>
                                <input asp-for="NewHoliday.Been" class="form-control NewHolidayBeen" />
                                <span asp-validation-for="NewHoliday.Been" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="NewHoliday.DateBeen" class="control-label"></label>
                                <input asp-for="NewHoliday.DateBeen" type="date"
                                    class="form-control NewHolidayDateBeen" />
                                <span asp-validation-for="NewHoliday.DateBeen" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="button" value="Add" class="btn btn-primary btnAddHoliday btnHolidayButtons" />
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="ValidationCheck" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Check it again bud</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <p class="errorText"></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        $('.form-control-chosen').chosen();
        dataTableInitialise();
    });
    $(".btnAddHoliday").on("click", function () {
        var pathname = window.location.pathname;
        var Country = $(".NewHolidayCountry").val();
        var City = $(".NewHolidayCity").val();
        var Been = $(".NewHolidayBeen").prop("checked");
        var DateBeen = $(".NewHolidayDateBeen").val();
        $.ajax({
            dataType: 'json',
            url: pathname,
            type: 'POST',
            data: {
                Country: Country,
                City: City,
                Been: Been,
                DateBeen: DateBeen
            },
            headers: {
                RequestVerificationToken:
                    $('input:hidden[name="__RequestVerificationToken"]').val()
            },
            success: function (response) {
                if (Number.isInteger(response)) {
                    window.location.replace("HolidayPot/View?Id=" + response);
                } else {
                    $("#ValidationCheck").modal();
                    $(".errorText").text(response);
                }
            },
            error: function () {
                alert("AJAX Request Failed, Contact Support");
            }
        });
    });
    window.addEventListener("resize", function () {
        dataTableInitialise();
    });
    function dataTableInitialise() {
        $('#HolidayTable').dataTable({
            "aoColumns": [
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "html" }
            ],
            "columnDefs": [
                { responsivePriority: 1, "targets": 0 },
                { responsivePriority: 3, "targets": 1 },
                { responsivePriority: 4, "targets": 2 },
                { responsivePriority: 5, "targets": 3 },
                { responsivePriority: 2, orderable: false, "targets": 4 }
            ],
            "pagingType": "numbers",
            "paging": false,
            "responsive": true,
            "order": [0, 'desc'],
            "destroy": true,
            "language": {
                "emptyTable": "No data available in table"
            },
            stateSave: true
        });
    }
</script>
}

Areas/HolidayPot/Pages/View.cshtml
@page
@model DatePot.Areas.HolidayPot.Pages.ViewModel

@{
    ViewData["Title"] = "View";
}
@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        const urlParams = new URLSearchParams(window.location.search);
        const redirectParam = urlParams.get('redirect');
        if (redirectParam == "update") {
            setTimeout(function () {
                $(".savedAlert").modal();
                $('.modal-backdrop').removeClass("modal-backdrop");
                setTimeout(function () {
                    $(".savedAlert").modal('hide');
                }, 1000);
            }, 250);
        }
        $('.form-control-chosen').chosen();
        checkCheck()
    });
    $(".btnUploadFile").on("click", function () {
        var pathname = '?handler=UploadFile';
        console.log($("#FormFile")[0])
        $.ajax({
            dataType: 'json',
            url: pathname,
            type: 'POST',
            data: {
                FormFile: $("#FormFile"),
            },
            headers: {
                RequestVerificationToken:
                    $('input:hidden[name="__RequestVerificationToken"]').val()
            },
            success: function (response) {
            },
            error: function () {
                alert("AJAX Request Failed, Contact Support");
            }
        });

    })
    function checkCheck() {
        var checkBox = document.getElementById("UpdateHolidayDetails_Been");
        var dateBeenRow = document.getElementById("dateBeenRow")
        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            dateBeenRow.style.display = "block";
        } else {
            dateBeenRow.style.display = "none";
        }
    }
</script>
}
<div class="modal fade savedAlert" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="alert alert-success text-center" role="alert">
            Saved successful!
        </div>
    </div>
</div>
<div class="fadeIn">
    @if (Model.HolidayDetails is null)
    {
        <h4>That Holiday has not been found.</h4>
        <h5>Would you like to create a Holiday instead?</h5>
        <a class="btn btn-primary" asp-page="/Index" asp-route-create="yes">Yes please!</a>
        <a class="btn btn-secondary" asp-page="/Index">No thank you</a>
    }
    else
    {
        <div class="row">
            <div class="col-6">
                <h1>Holiday Details</h1>
            </div>
            <div class="col-6">
                <a class="btn btn-primary float-right btnHolidayButtons" asp-page="/Index">Back</a>
                <button type="button" class="btn btn-danger float-right mr-2" data-toggle="modal"
                data-target="#ArchiveHoliday">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                        d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z" />
                    </svg>
                </button>
                <form method="post" asp-page-handler="Archive">
                    @Html.AntiForgeryToken()
                    <input value="@Model.HolidayDetails.HolidayID" asp-for="UpdateHolidayDetails.HolidayID" type="hidden" />
                    <div class="modal fade ArchiveHoliday" id="ArchiveHoliday" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Archive Holiday?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to do this?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary btnHolidayButtons">Yes I am sure!</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">I am big
                                        dumb</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card bg-light mb-2">
            <div class="card-body">
                <form method="post">
                    @Html.AntiForgeryToken()
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="UpdateHolidayDetails.HolidayID" value="@Model.HolidayDetails.HolidayID" type="hidden"
                    class="hidHolidayID" />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="UpdateHolidayDetails.Country" class="control-label"></label>
                                <input asp-for="UpdateHolidayDetails.Country" class="form-control UpdateHolidayCountry"
                                value="@Model.HolidayDetails.Country" required="required" type="text" />
                                <span asp-validation-for="UpdateHolidayDetails.Country" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="UpdateHolidayDetails.City" class="control-label"></label>
                                <input asp-for="UpdateHolidayDetails.City" class="form-control UpdateHolidayCity"
                                value="@Model.HolidayDetails.City" required="required" type="text" />
                                <span asp-validation-for="UpdateHolidayDetails.City" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="UpdateHolidayDetails.Been" class="control-label"></label>
                                <input asp-for="UpdateHolidayDetails.Been" checked="@Model.HolidayDetails.Been"
                                class="form-control UpdateHolidayBeen" onclick="checkCheck()" autocomplete="off" />
                                <span asp-validation-for="UpdateHolidayDetails.Been" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row" id="dateBeenRow">
                            <div class="col-12">
                                <label asp-for="UpdateHolidayDetails.DateBeen" class="control-label"></label>
                                @if (Model.HolidayDetails.DateBeen.ToString() == "01/01/0001 00:00:00")
                                {
                                    <input asp-for="UpdateHolidayDetails.DateBeen" class="form-control UpdateHolidayDateBeen"
                                        type="date" />
                                }
                                else
                                {
                                    <input asp-for="UpdateHolidayDetails.DateBeen" class="form-control UpdateHolidayDateBeen"
                                value="@Model.HolidayDetails.DateBeen.ToString("yyyy-MM-dd")" required="required"
                                type="date" />
                                }
                                <span asp-validation-for="UpdateHolidayDetails.DateBeen" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary btnUpdateHoliday btnHolidayButtons" />
                    </div>
                </form>
                <div class="row">
                    <div class="col-12">
                        <form method="post" asp-page="View" asp-page-handler="FileUpload" enctype="multipart/form-data">
                            <input value="@Model.HolidayDetails.HolidayID" type="hidden" name="HolidayID" />
                            <div class="row">
                                <div class="col-12">
                                    <h4>Pick photos to upload</h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <input type="file" name="photos" multiple="multiple" accept="image/*"
                                    class="custom-file-input-holiday" />
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col-12">
                                    <input type="submit" value="Upload" class="btn btn-primary btnHolidayButtons" />
                                </div>
                            </div>
                            <section class="row mt-2">
                                @if (Model.FileNameList != null && Model.FileNameList.Count > 0)
                                {
                                    @foreach (var item in Model.FileNameList)
                                    {
                                        <article>
                                            <img src="~/images/Holiday/@item.FileName" width="325px" style="border-radius:.25rem;"
                                    class="m-2" />
                                        </article>
                                    }
                                }
                            </section>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>