Areas/BeerPot/Models/Beers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;

namespace DatePot.Areas.BeerPot.Models
{
    public class Beers
    {
        public class BeerIndex
        {
            public List<BeerList> BeerList { get; set; }
        }
        public class BeerList
        {
            [Key]
            public int BeerID { get; set; }
            [Display(Name = "Name")]
            public string BeerName { get; set; }
            public string Brewery { get; set; }
            [Display(Name = "Average Wankyness")]
            public int AvgWankyness { get; set; }
            [Display(Name = "Average Taste")]
            public int AvgTaste { get; set; }
            [Display(Name = "Average Rating")]
            public int AvgRating { get; set; }
            public int? UserGroupID { get; set; }
            public List<RandomBeer> RandomBeer { get; set; }
        }
        public class NewBeer
        {
            [Required]
            [MaxLength(100, ErrorMessage = "Names must not exceed 100 characters")]
            [MinLength(2, ErrorMessage = "Names must be at least 2 characters long")]
            [DisplayName("Name")]
            public string BeerName { get; set; }
            public string Brewery { get; set; }
        }
        public class BeerDetails: BeerList
        {
        }
        public class UpdateBeerDetails: BeerDetails
        {
        }
        public class RandomBeer : BeerDetails 
        { 
        }
        public class BeerRatings 
        {
            public int BeerRatingID { get; set; }
            public int BeerID { get; set; }
            public string UserID { get; set; }
            public int Wankyness { get; set; }
            public int Taste { get; set; }
        }
    }
}

Areas/BeerPot/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
//using MySqlConnector;
using static DatePot.Areas.BeerPot.Models.Beers;
using DatePot.Areas.BeerPot.Data;
using static DatePot.Models.Site;
using Microsoft.AspNetCore.Identity;
using DatePot.Areas.Identity.Data;
using DatePot.Data;
using Microsoft.AspNetCore.Http;
using Serilog;

namespace DatePot.Areas.BeerPot.Pages
{
	[ValidateAntiForgeryToken]
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		private readonly IConfiguration _config;
		private readonly IBeerData _BeerData;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IIdentityData _identityData;
		private readonly ISiteData _siteData;
		public IndexModel(ILogger<IndexModel> logger,
		IConfiguration config,
		IBeerData BeerData,
		UserManager<IdentityUser> userManager,
		IIdentityData identityData,
		ISiteData siteData)
		{
			_logger = logger;
			_config = config;
			_BeerData = BeerData;
			_userManager = userManager;
			_identityData = identityData;
			_siteData = siteData;
		}
		public List<BeerList> Beers { get; set; }
		public NewBeer NewBeer { get; set; }
		public List<RandomBeer> RandomBeers { get; set; }
		public List<PotAccess> PotAccess { get; set; }
		public async Task<ActionResult> OnGet()
		{
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToPage("/Account/Login", new { area = "Identity" });
			}
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				var user = await _userManager.GetUserAsync(User);
				PotAccess = await _siteData.GetPotAccess(user.Id.ToString(), UserGroupID);
				int index = PotAccess.FindIndex(item => item.PotID == 6);
				if (index == -1)
				{
					return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
				}
				Beers = _BeerData.GetBeerList(UserGroupID).Result;

				return Page();
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<JsonResult> OnPost(string BeerName, string Brewery)
		{
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				JsonResult result = null;
				if (ModelState.IsValid == false)
				{
					foreach (var modelStateKey in ViewData.ModelState.Keys)
					{
						var value = ViewData.ModelState[modelStateKey];
						foreach (var error in value.Errors)
						{
							var errorMessage = error.ErrorMessage;
							result = new JsonResult(modelStateKey + ": " + errorMessage);
						}
					}
					return result;
				}
				int BeerID = _BeerData.AddBeer(BeerName, Brewery, UserGroupID).Result;

				result = new JsonResult(BeerID);
				return result;
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
	}
}

Areas/BeerPot/Pages/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using static DatePot.Areas.BeerPot.Models.Beers;
using DatePot.Areas.BeerPot.Data;
using static DatePot.Models.Site;
using Microsoft.AspNetCore.Identity;
using DatePot.Areas.Identity.Data;
using DatePot.Data;
using Microsoft.AspNetCore.Http;
using DatePot.Areas.FilmPot.Data;
using Serilog;

namespace DatePot.Areas.BeerPot.Pages
{
    [ValidateAntiForgeryToken]
	public class ViewModel : PageModel
	{
		private readonly IConfiguration _config;
		private readonly IBeerData _BeerData;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IIdentityData _identityData;
		private readonly ISiteData _siteData;
		private readonly IFilmData _filmData;
		public ViewModel(IConfiguration config,
		IBeerData BeerData,
		UserManager<IdentityUser> userManager,
		IIdentityData identityData,
		ISiteData siteData,
		IFilmData filmData)
		{
			_config = config;
			_BeerData = BeerData;
			_userManager = userManager;
			_identityData = identityData;
			_siteData = siteData;
			_filmData = filmData;
		}
		[BindProperty(SupportsGet = true)]
		public int Id { get; set; }
		[BindProperty]
		public UpdateBeerDetails UpdateBeerDetails { get; set; }

		public BeerDetails BeerDetails { get; set; }
		public List<BeerRatings> BeerRatingList { get; set; }
		public List<PotAccess> PotAccess { get; set; }
		public List<SelectListItem> Users { get; set; }
		public async Task<IActionResult> OnGet()
		{
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToPage("/Account/Login", new { area = "Identity" });
			}
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				var user = await _userManager.GetUserAsync(User);
				PotAccess = await _siteData.GetPotAccess(user.Id.ToString(), UserGroupID);
				int index = PotAccess.FindIndex(item => item.PotID == 6);
				if (index == -1)
				{
					return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
				}
				string cs = _config.GetConnectionString("Default");
				BeerDetails = _BeerData.GetBeerDetails(Id).Result.FirstOrDefault();
				if (BeerDetails.UserGroupID != UserGroupID)
                {
                    return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
                }
				var users = _siteData.GetUserList(UserGroupID, 6);
				BeerRatingList = await _BeerData.GetBeerRatings(BeerDetails.BeerID);
				Users = new List<SelectListItem>();
				users.Result.ForEach(x =>
				{
					Users.Add(new SelectListItem { Value = x.UserID.ToString(), Text = x.UserName });
				});
				return Page();
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<JsonResult> OnPost(int BeerID, string BeerName, string Brewery)
		{
			try
			{
				string cs = _config.GetConnectionString("Default");
				await _BeerData.UpdateBeer(BeerID, BeerName, Brewery);
				return new JsonResult(BeerID);

			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<IActionResult> OnPostArchive()
		{
			try
			{
				if (ModelState.IsValid == false)
				{
					return Page();
				}
				string cs = _config.GetConnectionString("Default");
				await _BeerData.ArchiveBeer(UpdateBeerDetails.BeerID);

				return RedirectToPage("./Index");
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<JsonResult> OnPostUpdateBeerRatings(string UserID, int Wankyness, int Taste, int BeerRatingID, int BeerID)
		{
			try
			{
				JsonResult result = null;
				if (ModelState.IsValid == false)
				{
					foreach (var modelStateKey in ViewData.ModelState.Keys)
					{
						var value = ViewData.ModelState[modelStateKey];
						foreach (var error in value.Errors)
						{
							var errorMessage = error.ErrorMessage;
							result = new JsonResult(modelStateKey + ": " + errorMessage);
						}
					}
					return result;
				}
				await _BeerData.UpdateBeerRating(UserID, Wankyness, Taste, BeerRatingID, BeerID);
				result = new JsonResult(1);
				return result;
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}

	}
}

Areas/FoodPot/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using static DatePot.Areas.FoodPot.Models.Food;
using DatePot.Areas.FoodPot.Data;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Identity;
using DatePot.Areas.Identity.Data;
using DatePot.Data;
using static DatePot.Models.Site;
using Microsoft.AspNetCore.Http;
using Serilog;

namespace DatePot.Areas.FoodPot.Pages
{
    [ValidateAntiForgeryToken]
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		private readonly IConfiguration _config;
		private readonly IFoodData _foodData;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IIdentityData _identityData;
		private readonly ISiteData _siteData;
		public IndexModel(ILogger<IndexModel> logger,
		IConfiguration config,
		IFoodData foodData,
		UserManager<IdentityUser> userManager,
		IIdentityData identityData,
		ISiteData siteData)
		{
			_logger = logger;
			_config = config;
			_foodData = foodData;
			_userManager = userManager;
			_identityData = identityData;
			_siteData = siteData;
		}
		public List<RestaurantList> Restaurants { get; set; }
		public List<SelectListItem> FoodType { get; set; }
		public List<SelectListItem> When { get; set; }
		public List<SelectListItem> Expense { get; set; }
		public List<SelectListItem> Location { get; set; }
		[BindProperty]
		public NewRestaurant NewRestaurant { get; set; }
		public NewFoodType NewFoodType { get; set; }
		public NewWhen NewWhen { get; set; }
		public List<RandomRestaurant> RandomRestaurants { get; set; }
		public List<PotAccess> PotAccess { get; set; }
		public async Task<ActionResult> OnGet()
		{
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToPage("/Account/Login", new { area = "Identity" });
			}
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				var user = await _userManager.GetUserAsync(User);
				PotAccess = await _siteData.GetPotAccess(user.Id.ToString(), UserGroupID);
				int index = PotAccess.FindIndex(item => item.PotID == 2);
				if (index == -1)
				{
					return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
				}
				Restaurants = _foodData.GetRestaurantList(UserGroupID).Result;
				var foodtypes = _foodData.GetFoodTypeList();
				var when = _foodData.GetWhenList();
				var expenses = _foodData.GetExpenseList();
				var locations = _foodData.GetLocationList();

				FoodType = new List<SelectListItem>();
				When = new List<SelectListItem>();
				Expense = new List<SelectListItem>();
				Location = new List<SelectListItem>();

				foodtypes.Result.ForEach(x =>
				{
					FoodType.Add(new SelectListItem { Value = x.FoodTypeID.ToString(), Text = x.FoodTypeText });
				});
				when.Result.ForEach(x =>
				{
					When.Add(new SelectListItem { Value = x.WhenID.ToString(), Text = x.WhenText });
				});
				expenses.Result.ForEach(x =>
				{
					Expense.Add(new SelectListItem { Value = x.ExpenseID.ToString(), Text = x.ExpenseText });
				});
				locations.Result.ForEach(x =>
				{
					Location.Add(new SelectListItem { Value = x.LocationID.ToString(), Text = x.LocationText });
				});

				return Page();
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public ActionResult OnPost(string RestaurantName, int ExpenseID, int LocationID, List<int> FoodType, List<int> When)
		{
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				JsonResult result = null;
				if (ModelState.IsValid == false)
				{
					foreach (var modelStateKey in ViewData.ModelState.Keys)
					{
						var value = ViewData.ModelState[modelStateKey];
						foreach (var error in value.Errors)
						{
							var errorMessage = error.ErrorMessage;
							result = new JsonResult(modelStateKey + ": " + errorMessage);
						}
					}
					return result;
				}
				int RestaurantID = _foodData.AddRestaurant(RestaurantName, ExpenseID, LocationID, UserGroupID).Result;

				foreach (var item in FoodType)
				{
					_foodData.AddRestaurantFoodType(RestaurantID, Convert.ToInt32(item));
				}
				foreach (var item in When)
				{
					_foodData.AddRestaurantWhen(RestaurantID, Convert.ToInt32(item));
				}

				result = new JsonResult(RestaurantID);
				return result;
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<IActionResult> OnPostFoodType()
		{
			try
			{
				if (!_foodData.FoodTypeDupeCheck(Request.Form["NewFoodType.FoodTypeText"].ToString()).Result)
				{
					await _foodData.AddFoodType(Request.Form["NewFoodType.FoodTypeText"].ToString());
					return RedirectToPage("./Index");
				}
				return RedirectToPage("./Index", new { @redirect = "FoodTypedupe", @value = Request.Form["NewFoodType.FoodTypeText"].ToString() });
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<IActionResult> OnPostWhen()
		{
			try
			{
				if (!_foodData.WhenDupeCheck(Request.Form["NewWhen.WhenText"].ToString()).Result)
				{
					await _foodData.AddWhen(Request.Form["NewWhen.WhenText"].ToString());
					return RedirectToPage("./Index");
				}
				return RedirectToPage("./Index", new { @redirect = "Whendupe", @value = Request.Form["NewWhen.WhenText"].ToString() });
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public async Task<IActionResult> OnPostRestaurantAttended()
		{
			try
			{
				return RedirectToPage("./Index", new { @redirect = "RestaurantAttended" });
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
		public PartialViewResult OnGetRandomRestaurant(int WhenID)
		{
			try
			{
				int? UserGroupID = HttpContext.Session.GetInt32("UserGroupID");
				RandomRestaurants = _foodData.GetRandomRestaurant(WhenID, UserGroupID).Result;
				return new PartialViewResult
				{
					ViewName = "_RandomRestaurant",
					ViewData = new ViewDataDictionary<List<RandomRestaurant>>(ViewData, RandomRestaurants)
				};
			}
			catch (Exception ex)
			{
				Log.Error(ex.ToString());
				throw new Exception(ex.ToString());
			}
		}
	}
}

Areas/BeerPot/Pages/View.cshtml
@page
@model DatePot.Areas.BeerPot.Pages.ViewModel

@{
    ViewData["Title"] = "View";
}
@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        const urlParams = new URLSearchParams(window.location.search);
        const redirectParam = urlParams.get('redirect');
        if (redirectParam == "update") {
            setTimeout(function () {
                $(".savedAlert").modal();
                $('.modal-backdrop').removeClass("modal-backdrop");
                setTimeout(function () {
                    $(".savedAlert").modal('hide');
                }, 1000);
            }, 250);
        }
        var items = @Html.Raw(Json.Serialize(Model.BeerRatingList));
        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            var sOptions = "";
            $(".UpdateBeerUserList option").each(function () {
                if (item.userID == $(this).val()) {
                    sOptions += "<option value='" + $(this).val() + "' selected>" + $(this).text() + "</option>"
                }
                sOptions += "<option value='" + $(this).val() + "'>" + $(this).text() + "</option>"
            })
            $(".ratingList").append(`
                    <div class='row pt-2 rating'>
                        <div class='col-4'>
                            <input type='hidden' id='BeerRatingID' value='` + item.beerRatingID + `' />
                            <label>Who</label>
                            <select class="form-control form-control-chosen AddRatingWhoID" data-placeholder="Choose a person..." required="required">
                                ` + sOptions + `
                            </select>
                        </div>
                        <div class='col-4'>
                            <label>Wankyness</label>
                            <input class='starRating WankynessVal' value=` + item.wankyness + ` data-size='xs'>
                        </div>
                        <div class='col-4'>
                            <label>Taste</label>
                            <input class='starRating TasteVal' value=` + item.taste + `  data-size='xs'>
                        </div>
                    </div>`
            )
        }
        $('.form-control-chosen').chosen();
        $(".starRating").rating({
            step: 1,
            showCaption: false,
            showClear: true,
            theme: 'krajee-svg'
        });
    });
    $(".btnAddRating").on("click", function () {
        var sOptions = "";
        $(".UpdateBeerUserList option").each(function () {
            sOptions += "<option value='" + $(this).val() + "'>" + $(this).text() + "</option>"
        })
        $(".ratingList").append(`
                <div class='row pt-2 rating'>
                    <div class='col-4'>
                        <input type='hidden' id='BeerRatingID' value='0' />
                        <label>Who</label>
                        <select class="form-control form-control-chosen AddRatingWhoID" data-placeholder="Choose a person..." required="required">
                            ` + sOptions + `
                        </select>
                    </div>
                    <div class='col-4'>
                        <label>Wankyness</label>
                        <input class='starRating WankynessVal' data-size='xs'>
                    </div>
                    <div class='col-4'>
                        <label>Taste</label>
                        <input class='starRating TasteVal' data-size='xs'>
                    </div>
                </div>`
        )
        $('.form-control-chosen').chosen();
        $(".starRating").rating({
            step: 1,
            showCaption: false,
            showClear: true,
            theme: 'krajee-svg'
        });
    })
    $(".btnUpdateBeer").on("click", function () {
        var BeerID = $(".hidBeerID").val();
        $(".rating").each(function () {
            console.log($(this).find(".AddRatingWhoID").chosen().val())
            var pathname = '?handler=UpdateBeerRatings';
            $.ajax({
                dataType: 'json',
                url: pathname,
                type: 'POST',
                data: {
                    UserID: $(this).find(".AddRatingWhoID").chosen().val(),
                    Wankyness: $(this).find(".WankynessVal").val(),
                    Taste: $(this).find(".TasteVal").val(),
                    BeerRatingID: $(this).find("#BeerRatingID").val(),
                    BeerID: BeerID
                },
                headers: {
                    RequestVerificationToken:
                        $('input:hidden[name="__RequestVerificationToken"]').val()
                },
                success: function (response) {
                    $.ajax({
                        dataType: 'json',
                        type: 'POST',
                        data: {
                            BeerID: BeerID,
                            BeerName: $(".UpdateBeerBeerName").val(),
                            Brewery: $(".UpdateBeerBrewery").val()
                        },
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (response) {
                            window.location.replace("View?Id=" + response + '&redirect=update');
                        },
                        error: function (error) {
                            console.log(error);
                        }
                    });
                },
                error: function () {
                    alert("AJAX Request Failed, Contact Support");
                }
            });
        })
    })
</script>
}
<div class="modal fade savedAlert" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="alert alert-success text-center" role="alert">
            Saved successful!
        </div>
    </div>
</div>
<div class="fadeIn">
    @if (Model.BeerDetails is null)
    {
        <h4>That Beer has not been found.</h4>
        <h5>Would you like to create a Beer instead?</h5>
        <a class="btn btn-primary" asp-page="/Index" asp-route-create="yes">Yes please!</a>
        <a class="btn btn-secondary" asp-page="/Index">No thank you</a>
    }
    else
    {
        <div class="row">
            <div class="col-6">
                <h1>Beer Details</h1>
            </div>
            <div class="col-6">
                <a class="btn btn-primary float-right btnBeerButtons" asp-page="/Index">Back</a>
                <button type="button" class="btn btn-danger float-right mr-2" data-toggle="modal"
                data-target="#ArchiveBeer">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                        d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z" />
                    </svg>
                </button>
                <form method="post" asp-page-handler="Archive">
                    @Html.AntiForgeryToken()
                    <input value="@Model.BeerDetails.BeerID" asp-for="UpdateBeerDetails.BeerID" type="hidden" />
                    <div class="modal fade ArchiveBeer" id="ArchiveBeer" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Archive Beer?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to do this?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary btnBeerButtons">Yes I am sure!</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">I am big
                                        dumb</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <select asp-items="Model.Users" class="form-control UpdateBeerUserList d-none"></select>
        <div class="card bg-light mb-2">
            <div class="card-body">
                <form method="post">
                    @Html.AntiForgeryToken()
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="UpdateBeerDetails.BeerID" value="@Model.BeerDetails.BeerID" type="hidden"
                    class="hidBeerID" />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="UpdateBeerDetails.BeerName" class="control-label"></label>
                                <input asp-for="UpdateBeerDetails.BeerName" class="form-control UpdateBeerBeerName"
                                value="@Model.BeerDetails.BeerName" required="required" type="text" />
                                <span asp-validation-for="UpdateBeerDetails.BeerName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label asp-for="UpdateBeerDetails.Brewery" class="control-label"></label>
                                <input asp-for="UpdateBeerDetails.Brewery" class="form-control UpdateBeerBrewery"
                                value="@Model.BeerDetails.Brewery" required="required" type="text" />
                                <span asp-validation-for="UpdateBeerDetails.Brewery" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label class="control-label">Rating</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body ratingList">
                                        <div class="row">
                                            <div class="col-12">
                                                <button type="button" class="btn btn-primary btnAddRating btnBeerButtons">Add
                                                    Rating</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="button" value="Save" class="btn btn-primary btnUpdateBeer btnBeerButtons" />
                    </div>
                </form>
            </div>
        </div>
    }
</div>

Areas/BeerPot/Pages/_RandomCoffee.cshtml
@model List<DatePot.Areas.CoffeePot.Models.Coffees.RandomCoffee>
<form method="post" asp-page-handler="RestaurantAttended">
    @if (Model.Count > 0)
    {
        <div class="modal-body">
            @foreach (var item in Model)
            {

                <input value="@item.CoffeeID" type="hidden" name="RestaurantID" />
                <p>
                    Today you guys are going to <strong>@item.CoffeeName</strong> Enjoy! ☕
                </p>
            }
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" onclick="return RandomCoffee();">No, another!!</button>
            <input type="submit" value="Let's do it!" class="btn btn-primary btnBeerButtons" />
        </div>
    }
    else
    {
        <div class="modal-body">
            <p>Looks like you are out of places to try. Add more to the Coffee Pot and try again!</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Will do boss</button>
        </div>
    }
</form>